[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sslcompare"
version = "0.1.0"
description = "Self-supervised learning comparison framework"
authors = [{ name = "Hayaru Shouno" }]
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "numpy",
    "scipy",
    "matplotlib",
    "pandas",
    "pillow",
    "jupyter",
    "ipykernel",
    "ipython",
    "ipywidgets",
    "joblib",
    "six",
    "pyyaml>=6.0",
    # "torchvision" は，.devcontainer の postCreateCommand で CUDA 対応版に
    # "torchvision",
    "lightning", # lightning はどうなんやろ．．．
    "wandb",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["sslcompare*"]
